version: "2"

services:
  #############################
  # ELASTICSEARCH MASTER NODE #
  #############################
  master:
    restart: unless-stopped
    image: blacktop/elasticsearch
    command: master
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic
  ####################################
  # ELASTICSEARCH CLIENT/INGEST NODE #
  ####################################
  client:
    restart: unless-stopped
    image: blacktop/elasticsearch:kopf
    command: client
    ports:
      - "9200:9200"
    links:
     - master:elastic-master
    networks:
      - elastic
  ###########################
  # ELASTICSEARCH DATA NODE #
  ###########################
  data:
    restart: unless-stopped
    image: blacktop/elasticsearch
    environment:
      - ES_HEAP_SIZE=2g
    command: data
    links:
     - master:elastic-master
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic
  ###############
  # KIBANA NODE #
  ###############
  kibana:
    image: kibana
    ports:
      - "80:5601"
    links:
     - client:elasticsearch
    networks:
      - elastic
#############################
# ELASTICSEARCH DATA VOLUME #
#############################
volumes:
  data:
################################
# ELASTICSEARCH BRIDGE NETWORK #
################################
networks:
  elastic:
    driver: bridge
