version: "2"

services:
  ####################################
  # ELASTICSEARCH CLIENT/INGEST NODE #
  ####################################
  es:
    restart: unless-stopped
    image: blacktop/elasticsearch
    ports:
      - "9200"
    networks:
      - elastic
  ###############
  # KIBANA NODE #
  ###############
  kibana:
    image: kibana
    ports:
      - "5601"
    links:
     - es:elasticsearch
    networks:
      - elastic
