version: "2"

services:
  ######################
  # ELASTICSEARCH NODE #
  ######################
  es:
    restart: unless-stopped
    image: blacktop/elasticsearch
    ports:
      - "9200"
  ###############
  # KIBANA NODE #
  ###############
  kibana:
    image: kibana
    ports:
      - "5601"
    links:
     - es:elasticsearch
